# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 12:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0003_auto_20160614_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=27700),
        ),
    ]
